package org.ng.search.data;
// Generated Jun 9, 2013 7:51:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Keywordlist generated by hbm2java
 */
public class Keywordlist implements java.io.Serializable {

	private Integer id;
	private String searchKey;
	private int keyCount;
	private Date searchDate;
	private byte isCrawled;
	private Date crawlDate;

	public Keywordlist() {
	}

	public Keywordlist(String searchKey, int keyCount, Date searchDate,
			byte isCrawled, Date crawlDate) {
		this.searchKey = searchKey;
		this.keyCount = keyCount;
		this.searchDate = searchDate;
		this.isCrawled = isCrawled;
		this.crawlDate = crawlDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSearchKey() {
		return this.searchKey;
	}

	public void setSearchKey(String searchKey) {
		this.searchKey = searchKey;
	}

	public int getKeyCount() {
		return this.keyCount;
	}

	public void setKeyCount(int keyCount) {
		this.keyCount = keyCount;
	}

	public Date getSearchDate() {
		return this.searchDate;
	}

	public void setSearchDate(Date searchDate) {
		this.searchDate = searchDate;
	}

	public byte getIsCrawled() {
		return this.isCrawled;
	}

	public void setIsCrawled(byte isCrawled) {
		this.isCrawled = isCrawled;
	}

	public Date getCrawlDate() {
		return this.crawlDate;
	}

	public void setCrawlDate(Date crawlDate) {
		this.crawlDate = crawlDate;
	}
	
	public int hashCode() {
		return this.getId().hashCode();
	}
	
	public boolean  equals(Object other) {
		if (this == other) return true;
		
		if (!(other instanceof Keywordlist)) 
			return false;
		
		Keywordlist otherObj = (Keywordlist)other;
		if (this.getId() == otherObj.getId()) {
			return true;
		} else {
			return false;
		}
	}

}
